# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.srcs/sources_1/ip/dmaCh1BufRam/dmaCh1BufRam.xci
# IP: The module: 'dmaCh1BufRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/ip/dmaCh1BufRam/dmaCh1BufRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaCh1BufRam'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.srcs/sources_1/ip/dmaCh1BufRam/dmaCh1BufRam.xci
# IP: The module: 'dmaCh1BufRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/ip/dmaCh1BufRam/dmaCh1BufRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaCh1BufRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
