# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tangerineA7_100.xdc

# IP: ip/systemRam/systemRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systemRam || ORIG_REF_NAME==systemRam} -quiet] -quiet

# Block Designs: bd/tangerineA7_100/tangerineA7_100.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100 || ORIG_REF_NAME==tangerineA7_100} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_0_0/tangerineA7_100_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_0_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_hdmiOut_0_0/tangerineA7_100_hdmiOut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_hdmiOut_0_0 || ORIG_REF_NAME==tangerineA7_100_hdmiOut_0_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_1_0/tangerineA7_100_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_1_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_1_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_xlslice_0_0/tangerineA7_100_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_xlslice_0_0 || ORIG_REF_NAME==tangerineA7_100_xlslice_0_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_xlconstant_0_0/tangerineA7_100_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_xlconstant_0_0 || ORIG_REF_NAME==tangerineA7_100_xlconstant_0_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/tangerineA7_100_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_system_ila_0_0 || ORIG_REF_NAME==tangerineA7_100_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/bd_2af6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6 || ORIG_REF_NAME==bd_2af6} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_0/bd_2af6_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_ila_lib_0 || ORIG_REF_NAME==bd_2af6_ila_lib_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_1/bd_2af6_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_g_inst_0 || ORIG_REF_NAME==bd_2af6_g_inst_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_2/bd_2af6_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_slot_0_aw_0 || ORIG_REF_NAME==bd_2af6_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_3/bd_2af6_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_slot_0_w_0 || ORIG_REF_NAME==bd_2af6_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_4/bd_2af6_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_slot_0_b_0 || ORIG_REF_NAME==bd_2af6_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_5/bd_2af6_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_slot_0_ar_0 || ORIG_REF_NAME==bd_2af6_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_6/bd_2af6_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2af6_slot_0_r_0 || ORIG_REF_NAME==bd_2af6_slot_0_r_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_tangerineMIGWrapper_0_0/tangerineA7_100_tangerineMIGWrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_tangerineMIGWrapper_0_0 || ORIG_REF_NAME==tangerineA7_100_tangerineMIGWrapper_0_0} -quiet] -quiet

# IP: ip/mig_7series_tangerine/mig_7series_tangerine.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_tangerine || ORIG_REF_NAME==mig_7series_tangerine} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_2_0/tangerineA7_100_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_2_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_2_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_xlslice_1_0/tangerineA7_100_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_xlslice_1_0 || ORIG_REF_NAME==tangerineA7_100_xlslice_1_0} -quiet] -quiet

# IP: bd/tangerineA7_100/ip/tangerineA7_100_tangerineSOC_0_0/tangerineA7_100_tangerineSOC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tangerineA7_100_tangerineSOC_0_0 || ORIG_REF_NAME==tangerineA7_100_tangerineSOC_0_0} -quiet] -quiet

# IP: ip/fpDiv/fpDiv.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpDiv || ORIG_REF_NAME==fpDiv} -quiet] -quiet

# IP: ip/fpMul/fpMul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpMul || ORIG_REF_NAME==fpMul} -quiet] -quiet

# IP: ip/fpAddSub/fpAddSub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpAddSub || ORIG_REF_NAME==fpAddSub} -quiet] -quiet

# IP: ip/ps2ControllerFifo/ps2ControllerFifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps2ControllerFifo || ORIG_REF_NAME==ps2ControllerFifo} -quiet] -quiet

# IP: ip/uartFiFo/uartFiFo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartFiFo || ORIG_REF_NAME==uartFiFo} -quiet] -quiet

# IP: ip/cacheTagRam/cacheTagRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cacheTagRam || ORIG_REF_NAME==cacheTagRam} -quiet] -quiet

# IP: ip/cacheDataRam/cacheDataRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cacheDataRam || ORIG_REF_NAME==cacheDataRam} -quiet] -quiet

# IP: ip/dmaCh1BufRam/dmaCh1BufRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaCh1BufRam || ORIG_REF_NAME==dmaCh1BufRam} -quiet] -quiet

# IP: ip/fontPROM/fontPROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fontPROM || ORIG_REF_NAME==fontPROM} -quiet] -quiet

# IP: ip/fastRam/fastRam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fastRam || ORIG_REF_NAME==fastRam} -quiet] -quiet

# IP: ip/systemRam/systemRam.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systemRam || ORIG_REF_NAME==systemRam} -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_0_0/tangerineA7_100_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_0_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_0_0/tangerineA7_100_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_0_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_0_0/tangerineA7_100_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_1_0/tangerineA7_100_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_1_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_1_0/tangerineA7_100_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_1_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_1_0/tangerineA7_100_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2af6_ila_lib_0 || ORIG_REF_NAME==bd_2af6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2af6_ila_lib_0 || ORIG_REF_NAME==bd_2af6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/ip/ip_0/bd_2af6_ila_lib_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/bd_0/bd_2af6_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_system_ila_0_0/tangerineA7_100_system_ila_0_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_2_0/tangerineA7_100_clk_wiz_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_2_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_2_0/tangerineA7_100_clk_wiz_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_2_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_2_0/tangerineA7_100_clk_wiz_2_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tangerineA7_100_clk_wiz_2_0 || ORIG_REF_NAME==tangerineA7_100_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/ip/tangerineA7_100_clk_wiz_2_0/tangerineA7_100_clk_wiz_2_0_ooc.xdc

# XDC: c:/Users/qubeck/Documents/Development/ProjektyVHDL/WukongBoard/tangerineA7_100/tangerineA7_100.gen/sources_1/bd/tangerineA7_100/tangerineA7_100_ooc.xdc
